<?php
echo \Mvc\System::getInstance()->viewDoctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Logs</title>

<!-- CSS Files -->
<?php
echo \Mvc\System::getInstance()->viewHeader() . PHP_EOL;
echo \Mvc\System::getInstance()->get('externalCss');
echo \Mvc\System::getInstance()->get('externalJavascript');
?>
<!--    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">-->
<!--    <!-- Optional theme -->
<!--    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">-->
</head>
<body>

<?php if (!is_null(\Mvc\System::getInstance()->viewNavi())) {?>
    <div id="navi" class="nav">
        <?php echo \Mvc\System::getInstance()->viewNavi();?>
    </div>
<?php
}

echo \Mvc\System::getInstance()->viewContentHeader();

echo \Mvc\System::getInstance()->viewContent();

echo \Mvc\System::getInstance()->viewFooter() . PHP_EOL;
?>
</body>
</html>