<div>
<?php
foreach ($this->filters as $filterName => $filterValues) { ?>
<div class="panel panel-default filter">
    <div class="panel-heading pointer" onclick="toggleFilter('<?php echo $filterName;?>')">
        <h3 class="panel-title"><?php echo $filterName; ?><span class="caret"></span></h3>
    </div>
    <div class="panel-body" id ="filterPanel_<?php echo $filterName;?>">
        <ul class="nav nav-pills" role="tablist">
            <?php
            foreach ($filterValues as $value) { ?>
                <li role="presentation" <?php
                if ($this->filtersActive && in_array($value, $this->filtersActive)) {echo 'class="active"';}
                ?>>
                    <a href="<?php echo $this->getRequest()->buildURL(array($filterName => $value), array('Index', 'Filter'));?>">
                        <?php echo $value; ?>
                    </a>
                </li>
            <?php
            } ?>
            <li role="presentation"><a href="<?php echo $this->getRequest()->buildURL(array($filterName => ''), array('Index', 'Filter'));?>">reset</a></li>
        </ul>
    </div>
</div>
<?php
}
?>
</div>