<ul class="nav nav-pills">
    <li role="presentation" class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
            Dropdown <span class="caret"></span>
        </a>
        <ul class="dropdown-menu" role="menu">
            <li><a href="#">Disabled link</a></li>
            <li><a href="#">Disabled link</a></li>
        </ul>
    </li>
</ul>