<div>
    <table class="table">
        <tr>
            <td>Entries (all): <?php echo $this->allEntries;?></td>
            <td class="label-success">Access logs: <?php echo $this->accessEntriesNumber;?></td>
            <td class="label-danger">Error logs: <?php echo $this->errorEntriesNumber;?></td>
            <td class="label-info">SysLog: <?php echo $this->syslogNumber;?></td>
            <td class="label-warning">Pydio: <?php echo $this->pydioNumber;?></td>
            <td class="label-default">Other logs: <?php echo $this->otherEntriesNumber;?></td>
        </tr>
    </table>
</div>

<h1>Latest Entries (Apache):</h1><br>
<?php
$i = 0;
foreach ($this->latestEntries as $entry) {
    $i++;
?>
    <div class="entry panel panel-default" id="entry<?php echo $i;?>">
        <div class="entryHeader panel-heading">Entry: <?php echo $i;?></div>
        <div class="entryBody panel-body">
            <table class="table table-striped">
            <?php foreach ($entry as $k => $v) {?>
                <tr>
                    <td><?php echo htmlentities($k);?></td>
                    <td><?php echo htmlentities($v);?></td>
                </tr>
            <?php }?>
            </table>
        </div>
    </div>
<?php
}